---
- name: Install tftpd-hpa server
  apt:
    name: tftpd-hpa

- name: Write configuration file
  template:
    src: tftpd-hpa.j2
    dest: /etc/default/tftpd-hpa
    owner: root
    group: tftp
    mode: 0640
  notify: Restart tftpd
    
- name: Create root directory
  file:
    path: "{{ tftpd_directory }}"
    state: directory
    owner: root
    group: tftp
    mode: 0750