---
- name: Install tftpd-hpa server
  apt:
    name: tftpd-hpa

- name: Write configuration file
  template:
    src: tftpd-hpa.j2
    dest: /etc/default/tftpd-hpa
    owner: root
    group: tftp
    mode: 0640
  notify: Restart tftpd
    
- name: Create root directory
  file:
    path: "{{ tftpd_directory }}"
    state: directory
    owner: "{{ tftpd_owner }}"
    group: "{{ tftpd_group }}"
    mode: "{{ tftpd_mode }}"

- name: Add users to tftp group
  user:
    append: yes
    groups: tftp
    name: "{{ item }}"
  with_items: "{{ tftpd_users }}"
